#!/bin/bash

# Secrets
kubectl apply -f secrets.yml

# MapConfig
kubectl apply -f mapconfig.yml

# MySQL
kubectl apply -f app-mysql.yml

# Zookeeper
kubectl apply -f app-zookeeper.yml

# Kafka
kubectl apply -f app-kafka.yml

# Votacao
kubectl apply -f app-votacao.yml

# Externo
minikube service app-votacao-votacao-service