version: "3"
services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: sam1436
      MYSQL_DATABASE: votacao
    ports:
      - "3306:3306"

  zookeeper:
    image: "bitnami/zookeeper:3.6.1"
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  broker:
    image: "bitnami/kafka:2.5.0"
    ports:
      - "9092:9092"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://broker:9092
    depends_on:
      - zookeeper
