timezone: America/Sao_Paulo

server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db:3306/votacao
    username: root
    password: sam1436
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

kafka:
  hosts: broker:9092

logging:
  level:
    org:
      springframework.web: INFO
      hibernate: INFO
  file: application.log

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure.include: info, health, metrics
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: true
